name: Expo Publish
on:
  push:
    tags:
      - test
jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - uses: expo/expo-github-action@v4
        with:
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
      - run: npm ci
      - run: npm test
      - run: sed -i 's/{{AD_UNIT_ID_IOS}}/${{ secrets.AD_UNIT_ID_IOS }}/g' configs.json
      - run: sed -i 's/{{AD_UNIT_ID_ANDROID}}/${{ secrets.AD_UNIT_ID_ANDROID }}/g' configs.json
      # - run: expo publish --release-channel production
